lint:
  actions_awsfulltest: false
  actions_awstest: false
  files_exist:
    - assets/email_template.html
    - assets/email_template.txt
    - assets/sendmail_template.txt
    - assets/nf-core-oncoflow_logo_light.png
    - docs/images/nf-core-oncoflow_logo_light.png
    - docs/images/nf-core-oncoflow_logo_dark.png
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - conf/test.config
    - tests/default.config
    - tests/default.nf.test
    - CODE_OF_CONDUCT.md
  files_unchanged:
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/ISSUE_TEMPLATE/feature_request.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/workflows/linting.yml
    - .prettierignore
    - assets/email_template.txt
    - docs/README.md
  multiqc_config: false
  nextflow_config:
    - params.input
    - params.outdir
    - timeline.enabled
    - trace.enabled
    - report.enabled
    - dag.enabled
nf_core_version: 4.0.2
repository_type: pipeline
template:
  author: Clinical Genomics Stockholm
  description: Pipeline cascade of nf-core/oncoanalyser + Clinical-Genomics/oncorefiner,
    written in Nextflow.
  force: false
  is_nfcore: false
  name: oncoflow
  org: Clinical-Genomics
  outdir: .
  skip_features:
    - igenomes
    - fastqc
    - multiqc
  version: 1.0.0dev
