# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "createoncorefinerparamsfile"
description: write your description here
keywords:
  - samplesheet
  - oncoanalyser
  - oncorefiner
tools:
  - "createoncorefinerparamsfile":
      description: "Generate a parameters file for the oncorefiner pipeline based on the output of the oncoanalyser pipeline."
      homepage: ""
      documentation: ""
      tool_dev_url: ""
      doi: ""
      licence: null
      identifier: null

input:
  - case_id:
      type: string
      description: Case ID
  - subject_id:
      type: string
      description: Subject ID
  - sample_id_tumor:
      type: string
      description: Sample ID of the tumor sample
  - sample_id_normal:
      type: string
      description: Sample ID of the normal sample
  - sex:
      type: string
      description: Sex of the patient
  - oncoanalyser_results_dir:
      type: directory
      description: Path to the output directory of the oncoanalyser pipeline
output:
  parameters_file:
    - "oncorefiner_params.yaml":
        type: file
        description: Parameters file for the oncorefiner pipeline
        pattern: "oncorefiner_params.yaml"
  versions_createoncorefinerparamsfile:
    - - ${task.process}:
          type: string
          description: The name of the process
      - createoncorefinerparamsfile:
          type: string
          description: The name of the tool
      - "1.0":
          type: string
          description: The version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - createoncorefinerparamsfile:
          type: string
          description: The name of the tool
      - "1.0":
          type: string
          description: The version of the tool
authors:
  - "@beatrizsavinhas"
maintainers:
  - "@beatrizsavinhas"
